name: Package and Release Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  HELM_VERSION: v3.18.2

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Lint chart
      run: helm lint .

    - name: Package chart
      run: |
        helm dependency update
        helm package . --destination ./target

    - name: Upload chart artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: helm-chart-${{ github.sha }}
        path: target/*.tgz
        retention-days: 30

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Download chart artifacts  
      uses: actions/download-artifact@v4.3.0
      with:
        name: helm-chart-${{ github.sha }}
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        files: ./artifacts/*.tgz
        generate_release_notes: true 