name: Taskfile Chart Build and Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.18.2'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI tasks (lint and test)
        run: task ci:default

      - name: Build and package chart
        run: task release

      - name: Upload chart artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-${{ github.sha }}
          path: target/*.tgz
          retention-days: 30

      - name: Log in to Container Registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push chart to OCI registry
        if: github.event_name == 'push' || github.event_name == 'release'
        run: |
          CHART_NAME=$(task helm:get-name)
          CHART_VERSION=$(task helm:get-version)
          # Push chart
          # helm push "target/${CHART_NAME}-${CHART_VERSION}.tgz" "oci://${{ env.REGISTRY }}/${{ github.repository_owner }}"
